<?php
/**
 *
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

require_once('User.class.php');

class WebPage {

	/**
     * L'entête de la page
     * @var String
     */
	private  $head = null;

	/**
     * Le titre de la page
     * @var String
     */
	private  $title = null;

	/**
     * Le corps de la page
     * @var String
     */
	private  $body = null;

    /**
     * Les script JS de la page
     * @var String
     */
    private $script = null;

	/**
     * Le constructeur
     * @param String $title Le titre de la page
     */
	public  function __construct(String $title = "") {
		$this->setTitle($title);
	}


	/**
     * Donne un titre à la page
     * @param String $title Le titre de la page
     */
	public  function setTitle(String $title) {
        $this->title = $title;
	}




    /**
     * Ajoute du code CSS à la page
     * @param  String $css Le code CSS
     * @return null
     */
    public  function appendCss(String $css) {
        $this->appendToHead("<style type='text/css'>{$css}</style>");
    }


    /**
     * Ajoute une feuille de style CSS à la page
     * @param  String $url L'URL de la feuille de style
     * @return null
     */
    public  function appendCssUrl(String $url) {
        $this->appendToHead("<link rel='stylesheet' type='text/css' href='{$url}'>");
    }


    /**
     * Ajoute du code JS à la page
     * @param  String $js Le code JS
     * @return null
     */
    public  function appendJs(String $js) {
        $this->appendToScript("<script type='text/javascript'>{$js}</script>");
    }


    /**
     * Ajoute un script JS à la page
     * @param  String $url L'URL du script JS
     * @return null
     */
    public  function appendJsUrl(String $url) {
        $this->appendToScript("<script type='text/javascript' src='{$url}'></script>");
    }


	/**
     * Ajoute du contenu à l'entête
     * @param  String $content Le contenu
     * @return null
     */
	public  function appendToHead(String $content) {
        $this->head .= $content;
	}


    /**
     * Ajoute du contenu au corps de la page
     * @param  String $content Le contenu
     * @return null
     */
    public  function appendContent(String $content) {
        $this->body .= $content;
    }


    /**
     * Ajoute les scripts JS
     * @param  String $content Le contenu
     * @return null
     */
    public function appendToScript(String $content) {
        $this->script .= $content;
    }


    /**
     * La page HTML avec tous les éléments
     * @return String La page HTML
     */
    public  function toHTML() {
        if (is_null($this->title)) {
            throw new Exception(__CLASS__ . ": title not set") ;
        }
        ob_start();
?>
        <!DOCTYPE html>
        <html>
        <head>
            <title><?= $this->title ?></title>
            <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <?= $this->head ?>
        </head>
        <body>
            <?= $this->body ?>
            <?= $this->script ?>
        </body>
        </html>
<?php
        return ob_get_clean();
    }
}
?>
